import {recommend,validateData,AREAS} from './scheduler.mjs';
const $=id=>document.getElementById(id);let data,draft;
const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
function members(){ $('members').replaceChildren();for(const m of data.members){const label=make('label','member');const box=make('input');box.type='checkbox';box.checked=true;box.value=m.email;const text=make('span','',m.name);text.append(make('small','',m.eligibleAreas.join(' · ')));label.append(box,text);$('members').append(label);box.addEventListener('change',invalidate);}}
function invalidate(){draft=null;$('export').disabled=true;$('schedule').replaceChildren(make('p','muted','Inputs changed. Generate a new draft to review these settings.'));$('stats').replaceChildren();}
function generate(){try{const services=$('day').value==='Sunday'?['1st Service','2nd Service','3rd Service','4th Service']:['Thursday Service'];const date=$('date').value;const weekday=new Date(`${date}T12:00:00Z`).getUTCDay();if(weekday!==($('day').value==='Sunday'?0:4))throw Error('Service date must match the selected Sunday or Thursday.');draft=recommend(data,{date,services,maxLoad:Number($('max').value),unavailable:[...$('members').querySelectorAll('input:not(:checked)')].map(e=>e.value)});$('error').textContent='';$('stats').replaceChildren();for(const [value,label] of [[draft.accepted,'REPORTS USED'],[draft.excluded,'RECORDS EXCLUDED'],[draft.unfilled,'UNFILLED POSITIONS']]){const stat=make('div','stat');stat.append(make('b','',value),make('span','',label));$('stats').append(stat);}$('schedule').replaceChildren();for(const service of services){const section=make('section','service');section.append(make('h3','',service));for(const a of draft.assignments.filter(a=>a.service===service).sort((a,b)=>AREAS.indexOf(a.area)-AREAS.indexOf(b.area))){const row=make('div','assignment');const detail=make('div');detail.append(make('div',a.member?'assignee':'assignee gap',a.member?.name||'Needs a member'),make('p','reason',a.reason));row.append(make('div','area',a.area),detail);section.append(row);}$('schedule').append(section);}$('export').disabled=false;}catch(e){$('error').textContent=e.message;invalidate();}}
async function demo(){data=validateData(await(await fetch('sample-data.json')).json());$('source').textContent='Synthetic demonstration data · fictional members';members();generate();}
$('import').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>10000000)throw Error('Choose a JSON export below 10 MB.');const next=validateData(JSON.parse(await f.text()));data=next;$('source').textContent=`Imported export · ${data.members.length} members · ${data.posts.length+data.observers.length} reports`;members();generate();}catch(err){$('error').textContent=err.message;}finally{e.target.value='';}});
for(const id of ['date','day','max'])$(id).addEventListener('change',invalidate);
$('generate').addEventListener('click',generate);$('reset').addEventListener('click',demo);
$('export').addEventListener('click',()=>{if(!draft)return;const url=URL.createObjectURL(new Blob([JSON.stringify({...draft,status:'DRAFT_REQUIRES_REVIEW',model:'rules-baseline-v0.1',source:$('source').textContent},null,2)],{type:'application/json'}));const a=make('a');a.href=url;a.download=`qc-posting-draft-${draft.date}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
demo().catch(e=>$('error').textContent=e.message);
